### ISSUE TITLE
HTTP ERROR: 503  SERVICE_UNAVAILABLE RequestURI=/  Powered by jetty://

### ISSUE THREAD

**Issue by maria95posteonet** [ghenry22/Subsonic_Synology#7]
It was working on my NAS, I had it playing a few songs from the webinterface. Then everything got unresponsive but there were DSM and other package updates, the new full reindexing of everything-search feature of the new DSM etc., so I thought it was because of this. 

Didn't really get better. So I uninstalled and reinstalled. While before, error message would simply be a browser warning like "site took too long to respond", it now almost immediately gives this error: 

HTTP ERROR: 503

SERVICE_UNAVAILABLE
RequestURI=/

Powered by jetty://

One suggestion online with this Subsonic error is to delete the database - but where is this stored ? I tried the usual locations and searched but can't find it. I deleted the jetty folder which is then recreated but that is not the same I think ? 

/volume1/@appstore/Subsonic/subsonic_sh.log says this:

38218 [main] INFO org.mortbay.log - jetty-6.1.x
76324 [main] WARN org.mortbay.log - Failed startup of context org.mortbay.jetty.webapp.WebAppContext@1083305{/,jar:file:/volume1/@appstore/Subsonic/subsonic.war!/}
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.mortbay.jetty.webapp.TagLibConfiguration.configureWebApp(TagLibConfiguration.java:171)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1215)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:500)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:117)
        at org.mortbay.jetty.Server.doStart(Server.java:217)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at net.sourceforge.subsonic.booter.deployer.SubsonicDeployer.deployWebApp(SubsonicDeployer.java:135)
        at net.sourceforge.subsonic.booter.deployer.SubsonicDeployer.<init>(SubsonicDeployer.java:65)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:100)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:61)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:877)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:839)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:264)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:261)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:185)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:164)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:429)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:728)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:380)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
        at net.sourceforge.subsonic.booter.Main.<init>(Main.java:24)
        at net.sourceforge.subsonic.booter.Main.main(Main.java:63)
91496 [main] INFO org.mortbay.log - Started SelectChannelConnector@0.0.0.0:4040
Subsonic running on: http://localhost:4040/
100541 [main] INFO org.springframework.remoting.rmi.RmiServiceExporter - Looking for RMI registry at port '9412'
104999 [main] INFO org.springframework.remoting.rmi.RmiServiceExporter - Could not detect RMI registry - creating new one
118618 [main] INFO org.springframework.remoting.rmi.RmiServiceExporter - Binding service 'SubsonicDeployerService' to RMI registry: RegistryImpl[UnicastServerRef [liveRef: [endpoint:[127.0.
0.1:9412](local),objID:[0:0:0, 0]]]]

I noticed at least one file (subsonic_package.log in root directory I think,that file just says Java user home is enabled, Subsonic log file accessed from DSM link just confirms Subsonic started successfully every time ) left over after uninstall, if there are other files left over that could be related ? Where and how would I find those files ? Madsonic had a detailed list of these at one point but doesn't apply for NAS or Subsonic installs. 

Next thing to try would be uninstall Subsonic again, also uninstall the required other packages - Perl and Python I think ? And then reinstall from there ? Problem is I think I have other packages related on those so DSM will not allow uninstall. That error message is a Python error message right ? 

Tried rebooting NAS and router, tried reapplying port forwarding rules in router, upnp is not enabled in Subsonic network settings (if I try it says "no upnp router found", port forwarding set manually anyway), stopping/waiting/starting package, stopping other packages to free up system resources. 

Only difference I can think of is the current build v6.0.1 vs the first one ? 

Thanks for your help :)

**Comment by maria95posteonet** [comment]
Update:

Saw the database "db" directory is in the same main Subsonic folder, it just didn't appear until hours after that package install was finished so for some reason it took a very long time for instructions to create that directory were put into place by Subsonic. 

Reinstalled the whole Subsonic package again a few times, eventually it started like normal and worked well long enough to set up initial settings etc. Ie. no 503 Jetty message.

But now, as opposed to when I first installed this package, media scan would not be successful it would seemingly initiate but the file count never started. I uninstalled everything again, deleted the subsonic daemon user in DSM Control Panel manually - I suppose that is one thing to note, that user should also be deleted when the package is uninstalled. Given how often permissions are an issue on Linux as well... 

So, Jetty problem disappeared by itself, new issue now this time is permissions - when I first installed this packet that was not a problem and I don't understand why now. So I am trying again now with a full reinstall yet again, after having deleted everything I could find inc the Synology username associated with that failed install. . 


> It was working on my NAS, I had it playing a few songs from the webinterface. Then everything got unresponsive but there were DSM and other package updates, the new full reindexing of everything-search feature of the new DSM etc., so I thought it was because of this. 

Didn't really get better. So I uninstalled and reinstalled. While before, error message would simply be a browser warning like "site took too long to respond", it now almost immediately gives this error: 

HTTP ERROR: 503

SERVICE_UNAVAILABLE
RequestURI=/

Powered by jetty://



One suggestion online with this Subsonic error is to delete the database - but where is this stored ? I tried the usual locations and searched but can't find it. I deleted the jetty folder which is then recreated but that is not the same I think ? 


/volume1/@appstore/Subsonic/subsonic_sh.log says this:

38218 [main] INFO org.mortbay.log - jetty-6.1.x
76324 [main] WARN org.mortbay.log - Failed startup of context org.mortbay.jetty.webapp.WebAppContext@1083305{/,jar:file:/volume1/@appstore/Subsonic/subsonic.war!/}
java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:219)
        at java.util.zip.ZipFile.<init>(ZipFile.java:149)
        at java.util.jar.JarFile.<init>(JarFile.java:166)
        at java.util.jar.JarFile.<init>(JarFile.java:130)
        at org.mortbay.jetty.webapp.TagLibConfiguration.configureWebApp(TagLibConfiguration.java:171)
        at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1215)
        at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:500)
        at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:448)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:117)
        at org.mortbay.jetty.Server.doStart(Server.java:217)
        at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:40)
        at net.sourceforge.subsonic.booter.deployer.SubsonicDeployer.deployWebApp(SubsonicDeployer.java:135)
        at net.sourceforge.subsonic.booter.deployer.SubsonicDeployer.<init>(SubsonicDeployer.java:65)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:100)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:61)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:877)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:839)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:440)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory$1.run(AbstractAutowireCapableBeanFactory.java:409)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:380)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:264)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:261)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:185)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:164)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:429)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:728)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:380)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
        at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
        at net.sourceforge.subsonic.booter.Main.<init>(Main.java:24)
        at net.sourceforge.subsonic.booter.Main.main(Main.java:63)
91496 [main] INFO org.mortbay.log - Started SelectChannelConnector@0.0.0.0:4040
Subsonic running on: http://localhost:4040/
100541 [main] INFO org.springframework.remoting.rmi.RmiServiceExporter - Looking for RMI registry at port '9412'
104999 [main] INFO org.springframework.remoting.rmi.RmiServiceExporter - Could not detect RMI registry - creating new one
118618 [main] INFO org.springframework.remoting.rmi.RmiServiceExporter - Binding service 'SubsonicDeployerService' to RMI registry: RegistryImpl[UnicastServerRef [liveRef: [endpoint:[127.0.
0.1:9412](local),objID:[0:0:0, 0]]]]





I noticed at least one file (subsonic_package.log in root directory I think,that file just says Java user home is enabled, Subsonic log file accessed from DSM link just confirms Subsonic started successfully every time ) left over after uninstall, if there are other files left over that could be related ? Where and how would I find those files ? Madsonic had a detailed list of these at one point but doesn't apply for NAS or Subsonic installs. 

Next thing to try would be uninstall Subsonic again, also uninstall the required other packages - Perl and Python I think ? And then reinstall from there ? Problem is I think I have other packages related on those so DSM will not allow uninstall. That error message is a Python error message right ? 

Tried rebooting NAS and router, tried reapplying port forwarding rules in router, upnp is not enabled in Subsonic network settings (if I try it says "no upnp router found", port forwarding set manually anyway), stopping/waiting/starting package, stopping other packages to free up system resources. 

Only difference I can think of is the current build v6.0.1 vs the first one ? 



Thanks for your help :)

**Comment by maria95posteonet** [comment]
-

**Comment by florian44470** [comment]
Hello, is maybe too late but this morning i have found the same error in my website. So i have check in the web and try something. For me it's worked i have all my playlist again. So : 

-Go in /var/subsonic/db and open subsonic.propreties.
-And simply add a 0 for cache_scale.

I don't know if is good but it's worked. All my playlist are here !
My file:

#HSQL Database Engine 1.8.0.5
#Sat Apr 21 20:15:37 CEST 2018
hsqldb.script_format=0
runtime.gc_interval=0
sql.enforce_strict_size=false
hsqldb.cache_size_scale=80 <=== i have add a 0
readonly=false
hsqldb.nio_data_file=true
hsqldb.cache_scale=140 <=== here too
version=1.8.0
hsqldb.default_table_type=memory
hsqldb.cache_file_scale=10 <=== and here
hsqldb.log_size=500 <=== modify by 500 for just test ^^
modified=yes
hsqldb.cache_version=1.7.0
hsqldb.original_version=1.8.0
hsqldb.compatible_version=1.8.0

I think is the limit of database, so i multiply this capacity by 10 ^^

**Comment by scienex** [comment]
> Hello, is maybe too late but this morning i have found the same error in my website. So i have check in the web and try something. For me it's worked i have all my playlist again. So :
> 
> -Go in /var/subsonic/db and open subsonic.propreties.
> -And simply add a 0 for cache_scale.
> 
> I don't know if is good but it's worked. All my playlist are here !
> My file:
> 
> #HSQL Database Engine 1.8.0.5
> #Sat Apr 21 20:15:37 CEST 2018
> hsqldb.script_format=0
> runtime.gc_interval=0
> sql.enforce_strict_size=false
> hsqldb.cache_size_scale=80 <=== i have add a 0
> readonly=false
> hsqldb.nio_data_file=true
> hsqldb.cache_scale=140 <=== here too
> version=1.8.0
> hsqldb.default_table_type=memory
> hsqldb.cache_file_scale=10 <=== and here
> hsqldb.log_size=500 <=== modify by 500 for just test ^^
> modified=yes
> hsqldb.cache_version=1.7.0
> hsqldb.original_version=1.8.0
> hsqldb.compatible_version=1.8.0
> 
> I think is the limit of database, so i multiply this capacity by 10 ^^

don't know how and why, but this worked for me as well!
thanks mate!

**Comment by ericpulvino** [comment]
This worked for me in 2019. No idea what was causing this.

**Comment by lukenukum** [comment]
> This worked for me in 2019. No idea what was causing this.

May 2019, same! although running on windows10 - same fix worked for me.

**Comment by Glenora** [comment]
Worked for me on Lubuntu in July 2019 also.
Thank you for this post.

**Comment by strydyr** [comment]
July 2019../

I'm running on Windows Server 2016. 

.properties file was in "C:\subsonic\db", and this worked.

Thanks!

**Comment by gothicpsyko** [comment]
worked for me aswell changing settings like you posted 

#HSQL Database Engine 1.8.0.5
#Sat Apr 21 20:15:37 CEST 2018
hsqldb.script_format=0
runtime.gc_interval=0
sql.enforce_strict_size=false
hsqldb.cache_size_scale=80 <=== i have add a 0
readonly=false
hsqldb.nio_data_file=true
hsqldb.cache_scale=140 <=== here too
version=1.8.0
hsqldb.default_table_type=memory
hsqldb.cache_file_scale=10 <=== and here
hsqldb.log_size=500 <=== modify by 500 for just test ^^
modified=yes
hsqldb.cache_version=1.7.0
hsqldb.original_version=1.8.0
hsqldb.compatible_version=1.8.0


Awesome! 
Running on a VM with server 2012, and thought it just was outdated now after alot of java updates the last time! 
this worked right on!  thx

**Comment by natuk** [comment]
In my case on Ubuntu 18.04 switching the default version of java to 8 did the trick.

**Comment by alcome1614** [comment]
> In my case on Ubuntu 18.04 switching the default version of java to 8 did the trick.

How could i do that. im on ubuntu 20.04

**Comment by blockfeed** [comment]
Ubuntu 24.04.2 LTS. Install openjdk-8-jre and add the following to /usr/bin/subsonic:
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
